locals {
	org_name = "Cleartoso"
	user_name = "terraform"
	user_password = "????????????????????????"
	vdc_name = "vDC-Cleartoso-Machelen"
	vdc_network_name = "orgnet-Direct-Cleartoso"
	vapp_name = "vApp-xyz"
	vapp_network_name = "vAppNet-xyz"
	vm1_name = "DC"
	vm2_name = "RDS"
	vm3_name = "FireboxV"
	template_catalog_name = "Public_Catalog"
	template_windows_name = "Win2022Template"
	template_watchguard_name = "FireboxVTemplate"
	}
